
name: CIFuzz
on: [push]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'nats'
        language: go
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'nats'
        fuzz-seconds: 600
        language: go
    - name: Upload Crash
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./out/artifacts 